docs/_navbar.md
docs/notes/index.md
docs/notes/lets-encrypt.md

Add documentation on setting up a LetsEncrypt SSL certificate for
a Node.js project.
Closes #XXXXX

feat: add lets encrypt

---

CONTRIBUTING.md

Setup instructions are added here
Closes #8

[DOC] - Added setup instructions

---

docs/_navbar.md
docs/git-commands/update-fork.md
docs/notes/index.md
docs/notes/lets-encrypt.md
docs/notes/sentry.md
docs/notes/winston.md

- Add Winston configuration (closes #13).
- Add Sentry configuration (closes #14).
- Update LetsEncrypt Boilerplate (closes #15)
- Add Update Fork script (closes #16)
Closes #XXXXX

feat: handle open issues

---

docs/_navbar.md
package-lock.json
package.json

Correct typo in the link for the nav bar.
Closes #XXXXX

fix: nav link

---

docs/index.html
package-lock.json
package.json

Implement Sentry through their CDN.
Closes #XXXXX

feat: implement sentry

---

docs/_navbar.md
docs/index.html
package-lock.json
package.json

Headers automatically get links that weren't working correctly.
Fixed.
Closes #XXXXX

fix: links in navbar

---

.github/workflows/markdown-lint.yml
docs/github-workflows/angular-deploy.md
docs/github-workflows/codeql-ts-node.md
docs/github-workflows/node-ci-ts.md
package-lock.json
package.json

chore: maintenance

---

docs/general/unix-commands.md

Adds the `netstat` command for checking active ports.
Closes #XXXXX

feat: add netstat command

---

docs/general/do-droplet-setup.md

Documents using `pm2` to set up a new application, replacing the use of `screen`.
Closes #XXXXX

feat: document pm2 use

---

docs/_navbar.md
docs/general/nginx-config.md
package-lock.json
package.json

Documents configuring a simple NGINX setup for handling multiple applications and subdomains on one machine.
Closes #XXXXX

feat: document nginx

---

docs/_navbar.md
docs/general/do-droplet-setup.md
package-lock.json
package.json

Document the process for performing maintenance on the Digital Ocean droplets.
Closes #XXXXX

feat: maintenance

---

docs/_navbar.md
docs/server-setup/index.md
docs/server-setup/maintenance.md
package-lock.json
package.json

Adds the steps for performing weekly server maintenance.
Closes #XXXXX

feat: weekly maintenance

---

docs/server-setup/set-alias.md
package-lock.json
package.json

Document setting up shortcuts for ssh hosts
Closes #XXXXX

feat: ssh alias

---

docs/_navbar.md
docs/server-setup/index.md
package-lock.json
package.json

Forgot to add the nav link for the new page.
Closes #XXXXX

fix: add link

---

docs/node-ts-config/eslint.md
docs/node-ts-config/index.md
package-lock.json
package.json

Expand the `eslint` configuration for stricter rules.
Closes #XXXXX

feat: more lint

---

docs/general/sentry.md
docs/general/winston.md
docs/node-ts-config/eslint.md
package-lock.json
package.json

feat: even more lint

---

docs/_navbar.md
docs/general/sentry.md
docs/github-workflows/index.md
docs/github-workflows/repository-setup.md
package-lock.json
package.json

Document the settings used when creating a new repository.
Closes #XXXXX

feat: document new repo settings

---

docs/_navbar.md
docs/general/bashrc-file.md
docs/general/index.md
package-lock.json
package.json

Add notes for my customisations to the `.bashrc` file.
Closes #XXXXX

feat: add bashrc notes

---

docs/server-setup/first-steps.md
package-lock.json
package.json

Add a timezone step to the new server setup.
Closes #XXXXX

fix: add timezone step

---

docs/node-ts-config/index.md

added typeScript at line no 6.

---

docs/_navbar.md
docs/index.html

feat: migrate analytics

---

docs/general/sentry.md

update docs (sentry.md)
Closes #76

update error default type to unknown and error to err

---

docs/github-workflows/angular-deploy.md
docs/github-workflows/codeql-ts-node.md
docs/github-workflows/node-ci-ts.md

Updates actions/checkout@v2 line to actions/checkout@v3 in the following files:
- https://github.com/nhcarrigan/notes/blob/main/docs/github-workflows/angular-deploy.md
- https://github.com/nhcarrigan/notes/blob/main/docs/github-workflows/codeql-ts-node.md
- https://github.com/nhcarrigan/notes/blob/main/docs/github-workflows/node-ci-ts.md
Closes #79

docs: update actions/checkout version to v3 (#79)

---

docs/index.html

feat: add background image

---

docs/funny-codes/index.md

Fixes the *view code* link from the *funny codes* md
Fix _view code_ link from the _funny-codes_ md
Closes #81

Fix "view code" link

---

docs/_navbar.md
docs/general/index.md
docs/general/slow-wsl-network.md

feat: document slow network fix

---

docs/index.html

feat: cursor

---

docs/index.html
docs/sw.js

This *should* enable a PWA. 
Closes #XXXXX

feat: pwa?

---

docs/favicon/site.webmanifest

fix: tweak manifest

---

docs/github-workflows/angular-deploy.md
docs/github-workflows/codeql-ts-node.md
docs/github-workflows/node-ci-ts.md

Updates actions/setup-node from version 2 to version 3 in files: 
- angular-deploy.md
- codeql-ts-node.md
- node-ci-ts.md
Closes #74

Update actions/setup-node version to 3

---

docs/index.html

fix: cursor url

---

.github/workflows/markdown-lint.yml
package.json

chore: node 18

---

docs/index.html

feat: add crisp

---

docs/_navbar.md
docs/github-workflows/dependency-validator.md
docs/github-workflows/index.md

docs: add dependency validator

---

docs/node-ts-config/eslint.md
docs/node-ts-config/index.md

chore: update linter config

---

docs/index.html

chore: update cursor link

---

.github/workflows/markdown-lint.yml
package.json

chore: move to node 20

---

docs/transfer-labels/templates.md

feat: add mentorship label
